markdown: rdiscount
highlighter: pygments
# permalink: /:year/:month/:day/:title.html
permalink: /:year/:month/:day/:title
name: "The hardest thing in the world is to insist"
markdown: rdiscount

author: "JohnWatsonDev"
atom-baseurl: "http://www.johnwatsondev.com"
disqus: "johnwatsondev"

navigations:
  - title: Archive
    class: fa fa-list-ul
    # href: /archive.html
    href: /archive/
  - title: Tags
    class: fa fa-tags
    # href: /tags.html
    href: /tags/
  - title: About
    class: fa fa-user
    # href: /about.html
    href: /about/
  # - title: Gallery
    # class: fa fa-film
    # href: http://foto.lhzhang.com
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml
